name: ubumwecommunitycenter
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^2.27.1
  google_fonts: ^6.1.0
  win32: ^5.9.0
  font_awesome_flutter: ^10.8.0
  go_router: ^13.2.0
  google_maps_flutter: ^2.10.0

flutter:
  uses-material-design: true
  assets:
    - assets/
  fonts:
    - family: Caveat
      fonts:
        - asset: fonts/Caveat/static/Caveat-Regular.ttf
        - asset: fonts/Caveat/static/Caveat-Medium.ttf
          weight: 500
        - asset: fonts/Caveat/static/Caveat-Bold.ttf
          weight: 700
    - family: Nunito
      fonts:
        - asset: fonts/Nunito/Nunito-VariableFont_wght.ttf
        - asset: fonts/Nunito/Nunito-Italic-VariableFont_wght.ttf
    # - family: MaterialIcons
    #   fonts:
    #     - asset: fonts/MaterialIcons-Regular.otf
    # - family: CupertinoIcons
    #   fonts:
    #     - asset: fonts/CupertinoIcons.ttf
    # - family: FontAwesome
    #   fonts:
    #     - asset: fonts/fa-brands-400.ttf

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0